title                    : "GitHub Pages 따라하기- devinlfe.github.io"
name                     : JHY
description              : 취미로 만든..
url                      : "https://wgd4253.github.io"
baseurl                  : 

disqus: True
disqus_shortname: wgd4253